[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino

monitor_speed = 115200

lib_deps =
    paulstoffregen/OneWire
    milesburton/DallasTemperature
    mikalhart/TinyGPSPlus
    mprograms/QMC5883LCompass
    bluerobotics/BlueRobotics MS5837 Library